### PR TITLE
Node Action

### PR DESCRIPTION
**Pull request by ibrahim0814**
Integrate bash uploader with node script

### CODE REVIEW

**Comment by s-weigand** [comment]
Thanks that you want to make this action work cross platform 😃 
But you shouldn't upload the `node_modules` folder, especially since only the `index.js` file and `action.yml` will be actually used. Instead compile the `index.js`file i.e. using [`@zeit/ncc`](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-a-javascript-action#commit-and-push-your-action-to-github).
Also you might want to have a look at [`@actions/exec`](https://github.com/actions/toolkit/tree/master/packages/exec) and [`@actions/tool-cache`](https://github.com/actions/toolkit/tree/master/packages/tool-cache).
I found that to test an action, it is best to integrate it in a dummy project, that includes the action the same way a user would.
If you want you can have a peek at [my action](https://github.com/s-weigand/setup-conda), which also uses quite some sys calls.

**Comment by ibrahim0814** [comment]
@s-weigand Thank you for you helpful suggestions!

**Comment by s-weigand** [comment]
I also would reommend you to base this on https://github.com/actions/typescript-action, since the typescript compiler/tslint gives a rich help with types and problems which can be caused by javascript.
The download can be simpilyed with [`actions/toolkit`](https://github.com/actions/toolkit):

```javascript
const io = require('@actions/io');
const tc = require('@actions/tool-cache');

const download_script = async () =>{
  const script_path = 'codecov.sh';
  const downloadpath= await tc.downloadTool('https://codecov.io/bash');
  await io.mv(downloadpath, script_path);
  return script_path;
}
```
Since async functions return a `Promise` you can just wait for the download and then run the script.

**Comment by ibrahim0814** [comment]
@s-weigand I'll try to see about converting this to TypeScript action. My initial thoughts are that the need isn't so dire just because there are < 100 lines of code in index.js, which is quite manageable with vanilla js

With regards to using @actions/io and @actions/tool-cache, I will also look into those options. I'm currently using callbacks to manage what code executes after the initial file download and it seems to be working fine on our test repo. 

I want to thank you again though for leading me onto @actions/exec - that was a superb suggestion without which I probably could not have finished working on this node action :)

**Review by Codes-Exe — APPROVED** [review]

**Pull request merged**
