### PR TITLE
feat: source `version` from package.json

### PR DESCRIPTION
**Pull request by RA80533**
- Sources the `version` property directly from package.json

### CODE REVIEW

**Comment by RA80533** [comment]
I noticed that the last commit made to `master` (prior to the PRs that were just merged) did not build the project accordingly. I didn't want to make any changes to the codebase to separate the changes to the final build.

@thomasrockhu Do you want to try to pull from master, run the build script, and apply any changes from it? I can rebase my branch off of it afterwards.

**Comment by thomasrockhu** [comment]
@RA80533 thanks for noticing that. I'll build something to make sure it's done before merges to `master`. 

In any case, I think we might go a different way with this PR. In particular removing the file altogether as described [here](https://github.com/codecov/codecov-action/issues/343). This way, it won't have to be maintained in two different places.

**Comment by RA80533** [comment]
Right now, there isn't any defined configuration for the environment for which the transpilers the project uses should target for transpilation. In other words, either ncc or tsc is making a guess that we're targeting some fairly old environment (it shouldn't be compiling from ES2015 to CommonJS). That guess also happens to be rolling with some regard because of the fact that we haven't defined exactly what we want to transpile to.

This is why there are funky changes to that file. Additionally, the version of the libraries used during the transpilation process may have had an impact on the final build.

I was going to open a separate issue specifically relating to the transpilation target for TypeScript because I believe ncc will pick up the configuration there accordingly.

**Comment by RA80533** [comment]
From what I understand, GitHub Actions requires there to be pre-built source code available for the runner to consume directly in the source repository from which the action is sourced. Was there some other method you were looking into that circumvented the need to track the distributed files?

**Comment by thomasrockhu** [comment]
Closing out due to https://github.com/codecov/codecov-action/pull/365

**Pull request closed without merging**
